#!/usr/bin/env bash


clean() {
  rm -f *.dec *.stats *.out
}

testing() {
  for f in ./*; do
    python ../arithmetic.py -e -i  $f -o $f.out >> $f.stats

    python ../arithmetic.py -d -i $f.out -o $f.dec
    printf "$f "
    if cmp  $f $f.dec > /dev/null 2>&1; then
      printf "[\033[1;32mPASS\033[m] \n"
    else
      printf "[\033[1;31mFAIL\033[m] \n"
    fi
  done
}

cd tests
clean
${1-testing}
